# Refresh configuration file
bind r source-file ~/.tmux.conf \; display-message "Configuration reloaded."

#set bash
set-option -g default-shell /bin/bash

# Disable default prefix
unbind C-b

# Toggle terminal mouse support.
bind m set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

# Toggle status bar. Useful for fullscreen focus.
bind t set-option status

# Add Ctrl+Space as Prefix
set -g prefix C-Space

# History
set -g history-limit 100000

# Enable mouse interactions
set -g mouse on

# Disable audible bell and monitor activity
set -g monitor-activity on
set -g activity-action none

# Enable 256 colors
set -g default-terminal "screen-256color"

# Set status bar color
set -g status-bg colour8

# customize how windows are displayed in the status line
set -g window-status-current-format "#[fg=colour8]#[bg=colour4]#[fg=colour7]#[bg=colour4] #I* #[fg=colour7] #W #[fg=colour4]#[bg=colour8]"
set -g window-status-format "#[fg=colour232]#[bg=colour8]#I.#[fg=colour232]  #W"

