# Refresh configuration file
bind r source-file ~/.tmux.conf \; display-message "Configuration reloaded."

#set bash
set-option -g default-shell /bin/bash
 
# Disable default prefix
unbind C-b
 
# Add Ctrl+Space as Prefix
set -g prefix C-Space
 
# Enable mouse interactions
set -g mouse on
 
# Enable 256 colors
set -g default-terminal "screen-256color"

# Set status bar color
set -g status-bg colour8
 
# customize how windows are displayed in the status line
set -g window-status-current-format "#[fg=colour8]#[bg=colour4]#[fg=colour7]#[bg=colour4] #I* #[fg=colour7] #W #[fg=colour4]#[bg=colour8]"
set -g window-status-format "#[fg=colour232]#[bg=colour8]#I.#[fg=colour232]  #W"

