---
name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Super-Linter
        uses: github/super-linter@v4.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

